version: "3.9"

services:
  rsyslog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rsyslog-loki-ingest
    ports:
      - "5514:5514"
    volumes:
      - ./sid_map.json:/data/sid_map.json
    depends_on:
      - loki
    networks:
      - hs-network

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - hs-network

networks:
  hs-network:
    external: true
